/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.Api;

import com.example.togowos.ApiCallback;
import com.example.togowos.ApiClient;
import com.example.togowos.ApiException;
import com.example.togowos.ApiResponse;
import com.example.togowos.Configuration;
import com.example.togowos.Pair;
import com.example.togowos.ProgressRequestBody;
import com.example.togowos.ProgressResponseBody;
import com.example.togowos.model.TripList;
import com.google.gson.reflect.TypeToken;

import org.threeten.bp.LocalDate;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TripApi {
    private ApiClient apiClient;

    public TripApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TripApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getTrip
     * @param originId origin stop id (optional)
     * @param originCoordLat origin latitude of center coordinate in the WGS84 system (optional)
     * @param originCoordLong origin longitude of center coordinate in the WGS84 system (optional)
     * @param originCoordName name of the address at the specified origin coordinate (optional)
     * @param destId destination stop id (optional)
     * @param destCoordLat destination latitude of center coordinate in the WGS84 system (optional)
     * @param destCoordLong destination longitude of center coordinate in the WGS84 system (optional)
     * @param destCoordName name of the address at the specified destination coordinate (optional)
     * @param viaId via stop/station id (optional)
     * @param date date of the trip (optional)
     * @param time time of the trip in format HH:MM (optional)
     * @param searchForArrival to specify that the given time and date is not the departure time but the latest time to arrive at the destination, set this parameter to the value 1. (optional)
     * @param useVas to exclude trips with Västtågen, set this parameter to 0. (optional)
     * @param useLDTrain to exclude trips with long distance trains, set this parameter to 0. (optional)
     * @param useRegTrain to exclude trips with regional trains, set this parameter to 0. (optional)
     * @param useBus to exclude trips with buses, set this parameter to 0. (optional)
     * @param useMedical to include medical transport lines trips with buses, set this parameter to 1. (optional)
     * @param originMedicalCon to search for medical transport connections from the origin, set this parameter to 1. (optional)
     * @param destMedicalCon to search for medical transport connections from the destination, set this parameter to 1. (optional)
     * @param wheelChairSpace to search for trips where at least one wheelchair space is present in the vehicle, set this parameter to 1. (optional)
     * @param strollerSpace to search for trips with space for stroller, baby carriage or rollator in the vehicle, set this parameter to 1. (optional)
     * @param lowFloor to search for trips where the vehicle is equipped with a low floor section, but not necessarily a ramp or lift, set this parameter to 1. (optional)
     * @param rampOrLift to search for trips where the vehicle is equipped with ramp or lift that allows fully barrier-free boarding and alighting, set this parameter to 1. (optional)
     * @param useBoat to exclude trips with boats, set this parameter to 0. (optional)
     * @param useTram to exclude trips with trams, set this parameter to 0. (optional)
     * @param usePT to exclude trips with public transportation, set this parameter to 0. (optional)
     * @param excludeDR to exclude journeys which require tel. registration, set this parameter to 1. (optional)
     * @param maxWalkDist maximum walking distance from/to the coordinate in meters (optional)
     * @param walkSpeed walking speed given in percent of normal speed (optional)
     * @param originWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param destWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param onlyWalk to search for walk-only trips, set this to 1 (optional)
     * @param originBike to search for trips with a bike ride from the origin to a nearby stop, where the journey continues using public transport, set this to 1. (optional)
     * @param maxBikeDist maximum biking distance from/to the coordinate in meters (optional)
     * @param bikeCriterion optimize for either the fastest route or a route that is made up of a larger percentage of bike road, where &#39;F&#39; is used to indicate tha fastest route with mimimized travel time, and &#39;D&#39; is used to indicate dedicated bike roads to maximize use of bike roads. (optional)
     * @param bikeProfile determines the altitude profile of the route, based on a setting for how fast the user can bike when it is steep, where &#39;E&#39; is used to indicate easy with minimized steepnes, &#39;N&#39; is used to indicate normal, and &#39;P&#39; is used to indicate powerful to allow more steepness. (optional)
     * @param onlyBike to search for bike-only trips, set this to 1 (optional)
     * @param originCar to search for trips where customer travels by car from the origin and is dropped off at a stop to continue the trip using public transport, set this to 1. (optional)
     * @param originCarWithParking to search for trips where the customer travels by car from the origin, parks at a commuter parking and walks to a nearby stop to continue the trip using public transport, set this to 1. (optional)
     * @param maxCarDist maximum car distance from/to the coordinate in meters (optional)
     * @param onlyCar to search for car-only trips, set this to 1 (optional)
     * @param maxChanges maximum number of changes in the trip (optional)
     * @param additionalChangeTime to prolong the minimal change times in minutes between the public transport legs of the returned journeys (optional)
     * @param disregardDefaultChangeMargin to ignore the default change margin, set this to 1 (optional)
     * @param needJourneyDetail if the reference URL for the journey detail service is not needed in the re, set this to 0 (optional)
     * @param needGeo if a reference link for each leg of the resulting trips, which can be used to request the geometry, is needed, set this to 1 (optional)
     * @param needItinerary if a reference link for each leg of the resulting trips, which can be used to request the itinerary, is needed, set this to 1 (optional)
     * @param numTrips the number of trips in the returned result (optional)
     * @param format the required response format (optional)
     * @param jsonpCallback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getTripCall(Long originId, Double originCoordLat, Double originCoordLong, String originCoordName, Long destId, Double destCoordLat, Double destCoordLong, String destCoordName, Long viaId, LocalDate date, String time, String searchForArrival, String useVas, String useLDTrain, String useRegTrain, String useBus, String useMedical, String originMedicalCon, String destMedicalCon, String wheelChairSpace, String strollerSpace, String lowFloor, String rampOrLift, String useBoat, String useTram, String usePT, String excludeDR, Integer maxWalkDist, String walkSpeed, String originWalk, String destWalk, String onlyWalk, String originBike, Integer maxBikeDist, String bikeCriterion, String bikeProfile, String onlyBike, String originCar, String originCarWithParking, Integer maxCarDist, String onlyCar, Integer maxChanges, Integer additionalChangeTime, String disregardDefaultChangeMargin, String needJourneyDetail, String needGeo, String needItinerary, Integer numTrips, String format, String jsonpCallback, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/trip";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (originId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originId", originId));
        if (originCoordLat != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originCoordLat", originCoordLat));
        if (originCoordLong != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originCoordLong", originCoordLong));
        if (originCoordName != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originCoordName", originCoordName));
        if (destId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("destId", destId));
        if (destCoordLat != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("destCoordLat", destCoordLat));
        if (destCoordLong != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("destCoordLong", destCoordLong));
        if (destCoordName != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("destCoordName", destCoordName));
        if (viaId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("viaId", viaId));
        if (date != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("date", date));
        if (time != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("time", time));
        if (searchForArrival != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("searchForArrival", searchForArrival));
        if (useVas != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useVas", useVas));
        if (useLDTrain != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useLDTrain", useLDTrain));
        if (useRegTrain != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useRegTrain", useRegTrain));
        if (useBus != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useBus", useBus));
        if (useMedical != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useMedical", useMedical));
        if (originMedicalCon != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originMedicalCon", originMedicalCon));
        if (destMedicalCon != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("destMedicalCon", destMedicalCon));
        if (wheelChairSpace != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("wheelChairSpace", wheelChairSpace));
        if (strollerSpace != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("strollerSpace", strollerSpace));
        if (lowFloor != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("lowFloor", lowFloor));
        if (rampOrLift != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rampOrLift", rampOrLift));
        if (useBoat != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useBoat", useBoat));
        if (useTram != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("useTram", useTram));
        if (usePT != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("usePT", usePT));
        if (excludeDR != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("excludeDR", excludeDR));
        if (maxWalkDist != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("maxWalkDist", maxWalkDist));
        if (walkSpeed != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("walkSpeed", walkSpeed));
        if (originWalk != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originWalk", originWalk));
        if (destWalk != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("destWalk", destWalk));
        if (onlyWalk != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("onlyWalk", onlyWalk));
        if (originBike != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originBike", originBike));
        if (maxBikeDist != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("maxBikeDist", maxBikeDist));
        if (bikeCriterion != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("bikeCriterion", bikeCriterion));
        if (bikeProfile != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("bikeProfile", bikeProfile));
        if (onlyBike != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("onlyBike", onlyBike));
        if (originCar != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originCar", originCar));
        if (originCarWithParking != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("originCarWithParking", originCarWithParking));
        if (maxCarDist != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("maxCarDist", maxCarDist));
        if (onlyCar != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("onlyCar", onlyCar));
        if (maxChanges != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("maxChanges", maxChanges));
        if (additionalChangeTime != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("additionalChangeTime", additionalChangeTime));
        if (disregardDefaultChangeMargin != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("disregardDefaultChangeMargin", disregardDefaultChangeMargin));
        if (needJourneyDetail != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("needJourneyDetail", needJourneyDetail));
        if (needGeo != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("needGeo", needGeo));
        if (needItinerary != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("needItinerary", needItinerary));
        if (numTrips != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("numTrips", numTrips));
        if (format != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("format", format));
        if (jsonpCallback != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("jsonpCallback", jsonpCallback));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {

        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getTripValidateBeforeCall(Long originId, Double originCoordLat, Double originCoordLong, String originCoordName, Long destId, Double destCoordLat, Double destCoordLong, String destCoordName, Long viaId, LocalDate date, String time, String searchForArrival, String useVas, String useLDTrain, String useRegTrain, String useBus, String useMedical, String originMedicalCon, String destMedicalCon, String wheelChairSpace, String strollerSpace, String lowFloor, String rampOrLift, String useBoat, String useTram, String usePT, String excludeDR, Integer maxWalkDist, String walkSpeed, String originWalk, String destWalk, String onlyWalk, String originBike, Integer maxBikeDist, String bikeCriterion, String bikeProfile, String onlyBike, String originCar, String originCarWithParking, Integer maxCarDist, String onlyCar, Integer maxChanges, Integer additionalChangeTime, String disregardDefaultChangeMargin, String needJourneyDetail, String needGeo, String needItinerary, Integer numTrips, String format, String jsonpCallback, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {


        com.squareup.okhttp.Call call = getTripCall(originId, originCoordLat, originCoordLong, originCoordName, destId, destCoordLat, destCoordLong, destCoordName, viaId, date, time, searchForArrival, useVas, useLDTrain, useRegTrain, useBus, useMedical, originMedicalCon, destMedicalCon, wheelChairSpace, strollerSpace, lowFloor, rampOrLift, useBoat, useTram, usePT, excludeDR, maxWalkDist, walkSpeed, originWalk, destWalk, onlyWalk, originBike, maxBikeDist, bikeCriterion, bikeProfile, onlyBike, originCar, originCarWithParking, maxCarDist, onlyCar, maxChanges, additionalChangeTime, disregardDefaultChangeMargin, needJourneyDetail, needGeo, needItinerary, numTrips, format, jsonpCallback, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Calculates a trip from a specified origin to a specified destination.
     * Calculates a trip from a specified origin to a specified destination. These might be stop/station IDs or coordinates based on addresses and points of interest validated by the location service or coordinates freely defined by the client. Parameters specifying both origin and destination are mandatory in calls to the trip service. When specifying a stop as origin, the parameter originId is used, while originCoordLat, originCoordLong, and originCoordName are used to specify a (named) coordinate. For the destination, the corresponding parameters are named either destId or destCoordLat, destCoordLong and destCoordName. It is also possible to define a via-stop/station. This forces the journey planner to search for trips which pass the defined station. The parameter is called viaId. When searching for a trip that goes via a coordinate, rather than a stop, two separate trip requests need to be combined into one.
     * @param originId origin stop id (optional)
     * @param originCoordLat origin latitude of center coordinate in the WGS84 system (optional)
     * @param originCoordLong origin longitude of center coordinate in the WGS84 system (optional)
     * @param originCoordName name of the address at the specified origin coordinate (optional)
     * @param destId destination stop id (optional)
     * @param destCoordLat destination latitude of center coordinate in the WGS84 system (optional)
     * @param destCoordLong destination longitude of center coordinate in the WGS84 system (optional)
     * @param destCoordName name of the address at the specified destination coordinate (optional)
     * @param viaId via stop/station id (optional)
     * @param date date of the trip (optional)
     * @param time time of the trip in format HH:MM (optional)
     * @param searchForArrival to specify that the given time and date is not the departure time but the latest time to arrive at the destination, set this parameter to the value 1. (optional)
     * @param useVas to exclude trips with Västtågen, set this parameter to 0. (optional)
     * @param useLDTrain to exclude trips with long distance trains, set this parameter to 0. (optional)
     * @param useRegTrain to exclude trips with regional trains, set this parameter to 0. (optional)
     * @param useBus to exclude trips with buses, set this parameter to 0. (optional)
     * @param useMedical to include medical transport lines trips with buses, set this parameter to 1. (optional)
     * @param originMedicalCon to search for medical transport connections from the origin, set this parameter to 1. (optional)
     * @param destMedicalCon to search for medical transport connections from the destination, set this parameter to 1. (optional)
     * @param wheelChairSpace to search for trips where at least one wheelchair space is present in the vehicle, set this parameter to 1. (optional)
     * @param strollerSpace to search for trips with space for stroller, baby carriage or rollator in the vehicle, set this parameter to 1. (optional)
     * @param lowFloor to search for trips where the vehicle is equipped with a low floor section, but not necessarily a ramp or lift, set this parameter to 1. (optional)
     * @param rampOrLift to search for trips where the vehicle is equipped with ramp or lift that allows fully barrier-free boarding and alighting, set this parameter to 1. (optional)
     * @param useBoat to exclude trips with boats, set this parameter to 0. (optional)
     * @param useTram to exclude trips with trams, set this parameter to 0. (optional)
     * @param usePT to exclude trips with public transportation, set this parameter to 0. (optional)
     * @param excludeDR to exclude journeys which require tel. registration, set this parameter to 1. (optional)
     * @param maxWalkDist maximum walking distance from/to the coordinate in meters (optional)
     * @param walkSpeed walking speed given in percent of normal speed (optional)
     * @param originWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param destWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param onlyWalk to search for walk-only trips, set this to 1 (optional)
     * @param originBike to search for trips with a bike ride from the origin to a nearby stop, where the journey continues using public transport, set this to 1. (optional)
     * @param maxBikeDist maximum biking distance from/to the coordinate in meters (optional)
     * @param bikeCriterion optimize for either the fastest route or a route that is made up of a larger percentage of bike road, where &#39;F&#39; is used to indicate tha fastest route with mimimized travel time, and &#39;D&#39; is used to indicate dedicated bike roads to maximize use of bike roads. (optional)
     * @param bikeProfile determines the altitude profile of the route, based on a setting for how fast the user can bike when it is steep, where &#39;E&#39; is used to indicate easy with minimized steepnes, &#39;N&#39; is used to indicate normal, and &#39;P&#39; is used to indicate powerful to allow more steepness. (optional)
     * @param onlyBike to search for bike-only trips, set this to 1 (optional)
     * @param originCar to search for trips where customer travels by car from the origin and is dropped off at a stop to continue the trip using public transport, set this to 1. (optional)
     * @param originCarWithParking to search for trips where the customer travels by car from the origin, parks at a commuter parking and walks to a nearby stop to continue the trip using public transport, set this to 1. (optional)
     * @param maxCarDist maximum car distance from/to the coordinate in meters (optional)
     * @param onlyCar to search for car-only trips, set this to 1 (optional)
     * @param maxChanges maximum number of changes in the trip (optional)
     * @param additionalChangeTime to prolong the minimal change times in minutes between the public transport legs of the returned journeys (optional)
     * @param disregardDefaultChangeMargin to ignore the default change margin, set this to 1 (optional)
     * @param needJourneyDetail if the reference URL for the journey detail service is not needed in the re, set this to 0 (optional)
     * @param needGeo if a reference link for each leg of the resulting trips, which can be used to request the geometry, is needed, set this to 1 (optional)
     * @param needItinerary if a reference link for each leg of the resulting trips, which can be used to request the itinerary, is needed, set this to 1 (optional)
     * @param numTrips the number of trips in the returned result (optional)
     * @param format the required response format (optional)
     * @param jsonpCallback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. (optional)
     * @return TripList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public TripList getTrip(Long originId, Double originCoordLat, Double originCoordLong, String originCoordName, Long destId, Double destCoordLat, Double destCoordLong, String destCoordName, Long viaId, LocalDate date, String time, String searchForArrival, String useVas, String useLDTrain, String useRegTrain, String useBus, String useMedical, String originMedicalCon, String destMedicalCon, String wheelChairSpace, String strollerSpace, String lowFloor, String rampOrLift, String useBoat, String useTram, String usePT, String excludeDR, Integer maxWalkDist, String walkSpeed, String originWalk, String destWalk, String onlyWalk, String originBike, Integer maxBikeDist, String bikeCriterion, String bikeProfile, String onlyBike, String originCar, String originCarWithParking, Integer maxCarDist, String onlyCar, Integer maxChanges, Integer additionalChangeTime, String disregardDefaultChangeMargin, String needJourneyDetail, String needGeo, String needItinerary, Integer numTrips, String format, String jsonpCallback) throws ApiException {
        ApiResponse<TripList> resp = getTripWithHttpInfo(originId, originCoordLat, originCoordLong, originCoordName, destId, destCoordLat, destCoordLong, destCoordName, viaId, date, time, searchForArrival, useVas, useLDTrain, useRegTrain, useBus, useMedical, originMedicalCon, destMedicalCon, wheelChairSpace, strollerSpace, lowFloor, rampOrLift, useBoat, useTram, usePT, excludeDR, maxWalkDist, walkSpeed, originWalk, destWalk, onlyWalk, originBike, maxBikeDist, bikeCriterion, bikeProfile, onlyBike, originCar, originCarWithParking, maxCarDist, onlyCar, maxChanges, additionalChangeTime, disregardDefaultChangeMargin, needJourneyDetail, needGeo, needItinerary, numTrips, format, jsonpCallback);
        return resp.getData();
    }

    /**
     * Calculates a trip from a specified origin to a specified destination.
     * Calculates a trip from a specified origin to a specified destination. These might be stop/station IDs or coordinates based on addresses and points of interest validated by the location service or coordinates freely defined by the client. Parameters specifying both origin and destination are mandatory in calls to the trip service. When specifying a stop as origin, the parameter originId is used, while originCoordLat, originCoordLong, and originCoordName are used to specify a (named) coordinate. For the destination, the corresponding parameters are named either destId or destCoordLat, destCoordLong and destCoordName. It is also possible to define a via-stop/station. This forces the journey planner to search for trips which pass the defined station. The parameter is called viaId. When searching for a trip that goes via a coordinate, rather than a stop, two separate trip requests need to be combined into one.
     * @param originId origin stop id (optional)
     * @param originCoordLat origin latitude of center coordinate in the WGS84 system (optional)
     * @param originCoordLong origin longitude of center coordinate in the WGS84 system (optional)
     * @param originCoordName name of the address at the specified origin coordinate (optional)
     * @param destId destination stop id (optional)
     * @param destCoordLat destination latitude of center coordinate in the WGS84 system (optional)
     * @param destCoordLong destination longitude of center coordinate in the WGS84 system (optional)
     * @param destCoordName name of the address at the specified destination coordinate (optional)
     * @param viaId via stop/station id (optional)
     * @param date date of the trip (optional)
     * @param time time of the trip in format HH:MM (optional)
     * @param searchForArrival to specify that the given time and date is not the departure time but the latest time to arrive at the destination, set this parameter to the value 1. (optional)
     * @param useVas to exclude trips with Västtågen, set this parameter to 0. (optional)
     * @param useLDTrain to exclude trips with long distance trains, set this parameter to 0. (optional)
     * @param useRegTrain to exclude trips with regional trains, set this parameter to 0. (optional)
     * @param useBus to exclude trips with buses, set this parameter to 0. (optional)
     * @param useMedical to include medical transport lines trips with buses, set this parameter to 1. (optional)
     * @param originMedicalCon to search for medical transport connections from the origin, set this parameter to 1. (optional)
     * @param destMedicalCon to search for medical transport connections from the destination, set this parameter to 1. (optional)
     * @param wheelChairSpace to search for trips where at least one wheelchair space is present in the vehicle, set this parameter to 1. (optional)
     * @param strollerSpace to search for trips with space for stroller, baby carriage or rollator in the vehicle, set this parameter to 1. (optional)
     * @param lowFloor to search for trips where the vehicle is equipped with a low floor section, but not necessarily a ramp or lift, set this parameter to 1. (optional)
     * @param rampOrLift to search for trips where the vehicle is equipped with ramp or lift that allows fully barrier-free boarding and alighting, set this parameter to 1. (optional)
     * @param useBoat to exclude trips with boats, set this parameter to 0. (optional)
     * @param useTram to exclude trips with trams, set this parameter to 0. (optional)
     * @param usePT to exclude trips with public transportation, set this parameter to 0. (optional)
     * @param excludeDR to exclude journeys which require tel. registration, set this parameter to 1. (optional)
     * @param maxWalkDist maximum walking distance from/to the coordinate in meters (optional)
     * @param walkSpeed walking speed given in percent of normal speed (optional)
     * @param originWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param destWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param onlyWalk to search for walk-only trips, set this to 1 (optional)
     * @param originBike to search for trips with a bike ride from the origin to a nearby stop, where the journey continues using public transport, set this to 1. (optional)
     * @param maxBikeDist maximum biking distance from/to the coordinate in meters (optional)
     * @param bikeCriterion optimize for either the fastest route or a route that is made up of a larger percentage of bike road, where &#39;F&#39; is used to indicate tha fastest route with mimimized travel time, and &#39;D&#39; is used to indicate dedicated bike roads to maximize use of bike roads. (optional)
     * @param bikeProfile determines the altitude profile of the route, based on a setting for how fast the user can bike when it is steep, where &#39;E&#39; is used to indicate easy with minimized steepnes, &#39;N&#39; is used to indicate normal, and &#39;P&#39; is used to indicate powerful to allow more steepness. (optional)
     * @param onlyBike to search for bike-only trips, set this to 1 (optional)
     * @param originCar to search for trips where customer travels by car from the origin and is dropped off at a stop to continue the trip using public transport, set this to 1. (optional)
     * @param originCarWithParking to search for trips where the customer travels by car from the origin, parks at a commuter parking and walks to a nearby stop to continue the trip using public transport, set this to 1. (optional)
     * @param maxCarDist maximum car distance from/to the coordinate in meters (optional)
     * @param onlyCar to search for car-only trips, set this to 1 (optional)
     * @param maxChanges maximum number of changes in the trip (optional)
     * @param additionalChangeTime to prolong the minimal change times in minutes between the public transport legs of the returned journeys (optional)
     * @param disregardDefaultChangeMargin to ignore the default change margin, set this to 1 (optional)
     * @param needJourneyDetail if the reference URL for the journey detail service is not needed in the re, set this to 0 (optional)
     * @param needGeo if a reference link for each leg of the resulting trips, which can be used to request the geometry, is needed, set this to 1 (optional)
     * @param needItinerary if a reference link for each leg of the resulting trips, which can be used to request the itinerary, is needed, set this to 1 (optional)
     * @param numTrips the number of trips in the returned result (optional)
     * @param format the required response format (optional)
     * @param jsonpCallback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. (optional)
     * @return ApiResponse&lt;TripList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<TripList> getTripWithHttpInfo(Long originId, Double originCoordLat, Double originCoordLong, String originCoordName, Long destId, Double destCoordLat, Double destCoordLong, String destCoordName, Long viaId, LocalDate date, String time, String searchForArrival, String useVas, String useLDTrain, String useRegTrain, String useBus, String useMedical, String originMedicalCon, String destMedicalCon, String wheelChairSpace, String strollerSpace, String lowFloor, String rampOrLift, String useBoat, String useTram, String usePT, String excludeDR, Integer maxWalkDist, String walkSpeed, String originWalk, String destWalk, String onlyWalk, String originBike, Integer maxBikeDist, String bikeCriterion, String bikeProfile, String onlyBike, String originCar, String originCarWithParking, Integer maxCarDist, String onlyCar, Integer maxChanges, Integer additionalChangeTime, String disregardDefaultChangeMargin, String needJourneyDetail, String needGeo, String needItinerary, Integer numTrips, String format, String jsonpCallback) throws ApiException {
        com.squareup.okhttp.Call call = getTripValidateBeforeCall(originId, originCoordLat, originCoordLong, originCoordName, destId, destCoordLat, destCoordLong, destCoordName, viaId, date, time, searchForArrival, useVas, useLDTrain, useRegTrain, useBus, useMedical, originMedicalCon, destMedicalCon, wheelChairSpace, strollerSpace, lowFloor, rampOrLift, useBoat, useTram, usePT, excludeDR, maxWalkDist, walkSpeed, originWalk, destWalk, onlyWalk, originBike, maxBikeDist, bikeCriterion, bikeProfile, onlyBike, originCar, originCarWithParking, maxCarDist, onlyCar, maxChanges, additionalChangeTime, disregardDefaultChangeMargin, needJourneyDetail, needGeo, needItinerary, numTrips, format, jsonpCallback, null, null);
        Type localVarReturnType = new TypeToken<TripList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Calculates a trip from a specified origin to a specified destination. (asynchronously)
     * Calculates a trip from a specified origin to a specified destination. These might be stop/station IDs or coordinates based on addresses and points of interest validated by the location service or coordinates freely defined by the client. Parameters specifying both origin and destination are mandatory in calls to the trip service. When specifying a stop as origin, the parameter originId is used, while originCoordLat, originCoordLong, and originCoordName are used to specify a (named) coordinate. For the destination, the corresponding parameters are named either destId or destCoordLat, destCoordLong and destCoordName. It is also possible to define a via-stop/station. This forces the journey planner to search for trips which pass the defined station. The parameter is called viaId. When searching for a trip that goes via a coordinate, rather than a stop, two separate trip requests need to be combined into one.
     * @param originId origin stop id (optional)
     * @param originCoordLat origin latitude of center coordinate in the WGS84 system (optional)
     * @param originCoordLong origin longitude of center coordinate in the WGS84 system (optional)
     * @param originCoordName name of the address at the specified origin coordinate (optional)
     * @param destId destination stop id (optional)
     * @param destCoordLat destination latitude of center coordinate in the WGS84 system (optional)
     * @param destCoordLong destination longitude of center coordinate in the WGS84 system (optional)
     * @param destCoordName name of the address at the specified destination coordinate (optional)
     * @param viaId via stop/station id (optional)
     * @param date date of the trip (optional)
     * @param time time of the trip in format HH:MM (optional)
     * @param searchForArrival to specify that the given time and date is not the departure time but the latest time to arrive at the destination, set this parameter to the value 1. (optional)
     * @param useVas to exclude trips with Västtågen, set this parameter to 0. (optional)
     * @param useLDTrain to exclude trips with long distance trains, set this parameter to 0. (optional)
     * @param useRegTrain to exclude trips with regional trains, set this parameter to 0. (optional)
     * @param useBus to exclude trips with buses, set this parameter to 0. (optional)
     * @param useMedical to include medical transport lines trips with buses, set this parameter to 1. (optional)
     * @param originMedicalCon to search for medical transport connections from the origin, set this parameter to 1. (optional)
     * @param destMedicalCon to search for medical transport connections from the destination, set this parameter to 1. (optional)
     * @param wheelChairSpace to search for trips where at least one wheelchair space is present in the vehicle, set this parameter to 1. (optional)
     * @param strollerSpace to search for trips with space for stroller, baby carriage or rollator in the vehicle, set this parameter to 1. (optional)
     * @param lowFloor to search for trips where the vehicle is equipped with a low floor section, but not necessarily a ramp or lift, set this parameter to 1. (optional)
     * @param rampOrLift to search for trips where the vehicle is equipped with ramp or lift that allows fully barrier-free boarding and alighting, set this parameter to 1. (optional)
     * @param useBoat to exclude trips with boats, set this parameter to 0. (optional)
     * @param useTram to exclude trips with trams, set this parameter to 0. (optional)
     * @param usePT to exclude trips with public transportation, set this parameter to 0. (optional)
     * @param excludeDR to exclude journeys which require tel. registration, set this parameter to 1. (optional)
     * @param maxWalkDist maximum walking distance from/to the coordinate in meters (optional)
     * @param walkSpeed walking speed given in percent of normal speed (optional)
     * @param originWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param destWalk to exclude trips with walks from/to coordinates, set this to 0 (optional)
     * @param onlyWalk to search for walk-only trips, set this to 1 (optional)
     * @param originBike to search for trips with a bike ride from the origin to a nearby stop, where the journey continues using public transport, set this to 1. (optional)
     * @param maxBikeDist maximum biking distance from/to the coordinate in meters (optional)
     * @param bikeCriterion optimize for either the fastest route or a route that is made up of a larger percentage of bike road, where &#39;F&#39; is used to indicate tha fastest route with mimimized travel time, and &#39;D&#39; is used to indicate dedicated bike roads to maximize use of bike roads. (optional)
     * @param bikeProfile determines the altitude profile of the route, based on a setting for how fast the user can bike when it is steep, where &#39;E&#39; is used to indicate easy with minimized steepnes, &#39;N&#39; is used to indicate normal, and &#39;P&#39; is used to indicate powerful to allow more steepness. (optional)
     * @param onlyBike to search for bike-only trips, set this to 1 (optional)
     * @param originCar to search for trips where customer travels by car from the origin and is dropped off at a stop to continue the trip using public transport, set this to 1. (optional)
     * @param originCarWithParking to search for trips where the customer travels by car from the origin, parks at a commuter parking and walks to a nearby stop to continue the trip using public transport, set this to 1. (optional)
     * @param maxCarDist maximum car distance from/to the coordinate in meters (optional)
     * @param onlyCar to search for car-only trips, set this to 1 (optional)
     * @param maxChanges maximum number of changes in the trip (optional)
     * @param additionalChangeTime to prolong the minimal change times in minutes between the public transport legs of the returned journeys (optional)
     * @param disregardDefaultChangeMargin to ignore the default change margin, set this to 1 (optional)
     * @param needJourneyDetail if the reference URL for the journey detail service is not needed in the re, set this to 0 (optional)
     * @param needGeo if a reference link for each leg of the resulting trips, which can be used to request the geometry, is needed, set this to 1 (optional)
     * @param needItinerary if a reference link for each leg of the resulting trips, which can be used to request the itinerary, is needed, set this to 1 (optional)
     * @param numTrips the number of trips in the returned result (optional)
     * @param format the required response format (optional)
     * @param jsonpCallback If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getTripAsync(Long originId, Double originCoordLat, Double originCoordLong, String originCoordName, Long destId, Double destCoordLat, Double destCoordLong, String destCoordName, Long viaId, LocalDate date, String time, String searchForArrival, String useVas, String useLDTrain, String useRegTrain, String useBus, String useMedical, String originMedicalCon, String destMedicalCon, String wheelChairSpace, String strollerSpace, String lowFloor, String rampOrLift, String useBoat, String useTram, String usePT, String excludeDR, Integer maxWalkDist, String walkSpeed, String originWalk, String destWalk, String onlyWalk, String originBike, Integer maxBikeDist, String bikeCriterion, String bikeProfile, String onlyBike, String originCar, String originCarWithParking, Integer maxCarDist, String onlyCar, Integer maxChanges, Integer additionalChangeTime, String disregardDefaultChangeMargin, String needJourneyDetail, String needGeo, String needItinerary, Integer numTrips, String format, String jsonpCallback, final ApiCallback<TripList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getTripValidateBeforeCall(originId, originCoordLat, originCoordLong, originCoordName, destId, destCoordLat, destCoordLong, destCoordName, viaId, date, time, searchForArrival, useVas, useLDTrain, useRegTrain, useBus, useMedical, originMedicalCon, destMedicalCon, wheelChairSpace, strollerSpace, lowFloor, rampOrLift, useBoat, useTram, usePT, excludeDR, maxWalkDist, walkSpeed, originWalk, destWalk, onlyWalk, originBike, maxBikeDist, bikeCriterion, bikeProfile, onlyBike, originCar, originCarWithParking, maxCarDist, onlyCar, maxChanges, additionalChangeTime, disregardDefaultChangeMargin, needJourneyDetail, needGeo, needItinerary, numTrips, format, jsonpCallback, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TripList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
