/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Color
 */
public class Color {
  @SerializedName("bgColor")
  private String bgColor = null;

  @SerializedName("fgColor")
  private String fgColor = null;

  @SerializedName("stroke")
  private String stroke = null;

  public Color bgColor(String bgColor) {
    this.bgColor = bgColor;
    return this;
  }

  /**
   * Backgroundcolor of this line
   * @return bgColor
   **/
  @ApiModelProperty(required = true, value = "Backgroundcolor of this line")
  public String getBgColor() {
    return bgColor;
  }

  public void setBgColor(String bgColor) {
    this.bgColor = bgColor;
  }

  public Color fgColor(String fgColor) {
    this.fgColor = fgColor;
    return this;
  }

  /**
   * Foregroundcolor of this line
   * @return fgColor
   **/
  @ApiModelProperty(required = true, value = "Foregroundcolor of this line")
  public String getFgColor() {
    return fgColor;
  }

  public void setFgColor(String fgColor) {
    this.fgColor = fgColor;
  }

  public Color stroke(String stroke) {
    this.stroke = stroke;
    return this;
  }

  /**
   * Stroke style of this line
   * @return stroke
   **/
  @ApiModelProperty(required = true, value = "Stroke style of this line")
  public String getStroke() {
    return stroke;
  }

  public void setStroke(String stroke) {
    this.stroke = stroke;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Color color = (Color) o;
    return Objects.equals(this.bgColor, color.bgColor) &&
            Objects.equals(this.fgColor, color.fgColor) &&
            Objects.equals(this.stroke, color.stroke);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bgColor, fgColor, stroke);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Color {\n");

    sb.append("    bgColor: ").append(toIndentedString(bgColor)).append("\n");
    sb.append("    fgColor: ").append(toIndentedString(fgColor)).append("\n");
    sb.append("    stroke: ").append(toIndentedString(stroke)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

