/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Direction
 */
public class Direction {
  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;

  @SerializedName("$")
  private String value = null;

  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;

  public Direction routeIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
    return this;
  }

   /**
   * End of validity on total route
   * @return routeIdxTo
  **/
  @ApiModelProperty(required = true, value = "End of validity on total route")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }

  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  public Direction value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Direction routeIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
    return this;
  }

   /**
   * Start of validity on total route
   * @return routeIdxFrom
  **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }

  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Direction direction = (Direction) o;
    return Objects.equals(this.routeIdxTo, direction.routeIdxTo) &&
        Objects.equals(this.value, direction.value) &&
        Objects.equals(this.routeIdxFrom, direction.routeIdxFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeIdxTo, value, routeIdxFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Direction {\n");

    sb.append("    routeIdxTo: ").append(toIndentedString(routeIdxTo)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    routeIdxFrom: ").append(toIndentedString(routeIdxFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

