/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.example.togowos.model.Points;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * Geometry
 */
public class Geometry {
  @SerializedName("errorText")
  private String errorText = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("serverdate")
  private LocalDate serverdate = null;

  @SerializedName("servertime")
  private String servertime = null;

  @SerializedName("Points")
  private List<Points> points = null;

  @SerializedName("noNamespaceSchemaLocation")
  private String noNamespaceSchemaLocation = null;

  public Geometry errorText(String errorText) {
    this.errorText = errorText;
    return this;
  }

  /**
   * Get errorText
   * @return errorText
   **/
  @ApiModelProperty(value = "")
  public String getErrorText() {
    return errorText;
  }

  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  public Geometry error(String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public Geometry serverdate(LocalDate serverdate) {
    this.serverdate = serverdate;
    return this;
  }

  /**
   * Get serverdate
   * @return serverdate
   **/
  @ApiModelProperty(value = "")
  public LocalDate getServerdate() {
    return serverdate;
  }

  public void setServerdate(LocalDate serverdate) {
    this.serverdate = serverdate;
  }

  public Geometry servertime(String servertime) {
    this.servertime = servertime;
    return this;
  }

  /**
   * Current server time in format HH:MM
   * @return servertime
   **/
  @ApiModelProperty(value = "Current server time in format HH:MM")
  public String getServertime() {
    return servertime;
  }

  public void setServertime(String servertime) {
    this.servertime = servertime;
  }

  public Geometry points(List<Points> points) {
    this.points = points;
    return this;
  }

  public Geometry addPointsItem(Points pointsItem) {
    if (this.points == null) {
      this.points = new ArrayList<Points>();
    }
    this.points.add(pointsItem);
    return this;
  }

  /**
   * Get points
   * @return points
   **/
  @ApiModelProperty(value = "")
  public List<Points> getPoints() {
    return points;
  }

  public void setPoints(List<Points> points) {
    this.points = points;
  }

  public Geometry noNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
    return this;
  }

  /**
   * Get noNamespaceSchemaLocation
   * @return noNamespaceSchemaLocation
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNoNamespaceSchemaLocation() {
    return noNamespaceSchemaLocation;
  }

  public void setNoNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Geometry geometry = (Geometry) o;
    return Objects.equals(this.errorText, geometry.errorText) &&
            Objects.equals(this.error, geometry.error) &&
            Objects.equals(this.serverdate, geometry.serverdate) &&
            Objects.equals(this.servertime, geometry.servertime) &&
            Objects.equals(this.points, geometry.points) &&
            Objects.equals(this.noNamespaceSchemaLocation, geometry.noNamespaceSchemaLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorText, error, serverdate, servertime, points, noNamespaceSchemaLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Geometry {\n");

    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    serverdate: ").append(toIndentedString(serverdate)).append("\n");
    sb.append("    servertime: ").append(toIndentedString(servertime)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    noNamespaceSchemaLocation: ").append(toIndentedString(noNamespaceSchemaLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

