/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * GeometryRef
 */
public class GeometryRef {
  @SerializedName("ref")
  private String ref = null;

  public GeometryRef ref(String ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Contains a URL to call the REST interface for geometry
   * @return ref
  **/
  @ApiModelProperty(required = true, value = "Contains a URL to call the REST interface for geometry")
  public String getRef() {
    return ref;
  }

  public void setRef(String ref) {
    this.ref = ref;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeometryRef geometryRef = (GeometryRef) o;
    return Objects.equals(this.ref, geometryRef.ref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ref);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeometryRef {\n");

    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

