/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * JourneyName
 */
public class JourneyName {
  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;

  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;

  @SerializedName("name")
  private String name = null;

  public JourneyName routeIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
    return this;
  }

   /**
   * End of validity on total route.
   * @return routeIdxTo
  **/
  @ApiModelProperty(required = true, value = "End of validity on total route.")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }

  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  public JourneyName routeIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
    return this;
  }

   /**
   * Start of validity on total route
   * @return routeIdxFrom
  **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }

  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }

  public JourneyName name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name to be displayed
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name to be displayed")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyName journeyName = (JourneyName) o;
    return Objects.equals(this.routeIdxTo, journeyName.routeIdxTo) &&
        Objects.equals(this.routeIdxFrom, journeyName.routeIdxFrom) &&
        Objects.equals(this.name, journeyName.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeIdxTo, routeIdxFrom, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyName {\n");

    sb.append("    routeIdxTo: ").append(toIndentedString(routeIdxTo)).append("\n");
    sb.append("    routeIdxFrom: ").append(toIndentedString(routeIdxFrom)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

