/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.togowos.Api.*;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JourneyId
 */
public class JourneyId {
  @SerializedName("id")
  private String id = null;

  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;

  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;

  public JourneyId id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of this journey
   * @return id
  **/
  @ApiModelProperty(required = true, value = "ID of this journey")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public JourneyId routeIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
    return this;
  }

   /**
   * End of validity on total route
   * @return routeIdxTo
  **/
  @ApiModelProperty(required = true, value = "End of validity on total route")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }

  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  public JourneyId routeIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
    return this;
  }

   /**
   * Start of validity on total route
   * @return routeIdxFrom
  **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }

  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyId journeyId = (JourneyId) o;
    return Objects.equals(this.id, journeyId.id) &&
        Objects.equals(this.routeIdxTo, journeyId.routeIdxTo) &&
        Objects.equals(this.routeIdxFrom, journeyId.routeIdxFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, routeIdxTo, routeIdxFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyId {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    routeIdxTo: ").append(toIndentedString(routeIdxTo)).append("\n");
    sb.append("    routeIdxFrom: ").append(toIndentedString(routeIdxFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

