/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.example.togowos.Api.*;
import io.swagger.annotations.ApiModelProperty;
import com.example.togowos.model.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Points
 */
public class Points {
  @SerializedName("Point")
  private List<Point> point = new ArrayList<Point>();

  public Points point(List<Point> point) {
    this.point = point;
    return this;
  }

  public Points addPointItem(Point pointItem) {
    this.point.add(pointItem);
    return this;
  }

   /**
   * Get point
   * @return point
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Point> getPoint() {
    return point;
  }

  public void setPoint(List<Point> point) {
    this.point = point;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Points points = (Points) o;
    return Objects.equals(this.point, points.point);
  }

  @Override
  public int hashCode() {
    return Objects.hash(point);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Points {\n");

    sb.append("    point: ").append(toIndentedString(point)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

