/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * StopLocation
 */
public class StopLocation {
  @SerializedName("id")
  private String id = null;

  @SerializedName("lon")
  private String lon = null;

  @SerializedName("idx")
  private String idx = null;

  @SerializedName("weight")
  private String weight = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("track")
  private String track = null;

  @SerializedName("lat")
  private String lat = null;


  public StopLocation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * This ID can either be used as originId or destId to perform a trip request or to call a departure  board
   * @return id
  **/
  @ApiModelProperty(required = true, value = "This ID can either be used as originId or destId to perform a trip request or to call a departure  board")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public StopLocation lon(String lon) {
    this.lon = lon;
    return this;
  }

   /**
   * The WGS84 longitude
   * @return lon
  **/
  @ApiModelProperty(required = true, value = "The WGS84 longitude")
  public String getLon() {
    return lon;
  }

  public void setLon(String lon) {
    this.lon = lon;
  }

  public StopLocation idx(String idx) {
    this.idx = idx;
    return this;
  }

   /**
   * This index can be used to reorder the StopLocations and CoordLocations in JSON format response to their correct order. IN JSON you can receive two arrays, one for Stops and one for Addresses. This attribute is only contained in reponses to the location.name request. The location with idx&#x3D;1 is the best fitting location
   * @return idx
  **/
  @ApiModelProperty(required = true, value = "This index can be used to reorder the StopLocations and CoordLocations in JSON format response to their correct order. IN JSON you can receive two arrays, one for Stops and one for Addresses. This attribute is only contained in reponses to the location.name request. The location with idx=1 is the best fitting location")
  public String getIdx() {
    return idx;
  }

  public void setIdx(String idx) {
    this.idx = idx;
  }

  public StopLocation weight(String weight) {
    this.weight = weight;
    return this;
  }

   /**
   * This value specifies some kind of importance of this stop. The more traffic at this stop the higher the weight. The range is between 0 and 32767. This attribute is just contained in the location.allstops response
   * @return weight
  **/
  @ApiModelProperty(value = "This value specifies some kind of importance of this stop. The more traffic at this stop the higher the weight. The range is between 0 and 32767. This attribute is just contained in the location.allstops response")
  public String getWeight() {
    return weight;
  }

  public void setWeight(String weight) {
    this.weight = weight;
  }

  public StopLocation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Contains the output name of this stop or station
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Contains the output name of this stop or station")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public StopLocation track(String track) {
    this.track = track;
    return this;
  }

   /**
   * Track information, if available
   * @return track
  **/
  @ApiModelProperty(value = "Track information, if available")
  public String getTrack() {
    return track;
  }

  public void setTrack(String track) {
    this.track = track;
  }

  public StopLocation lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * The WGS84 latitude
   * @return lat
  **/
  @ApiModelProperty(required = true, value = "The WGS84 latitude")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopLocation stopLocation = (StopLocation) o;
    return Objects.equals(this.id, stopLocation.id) &&
        Objects.equals(this.lon, stopLocation.lon) &&
        Objects.equals(this.idx, stopLocation.idx) &&
        Objects.equals(this.weight, stopLocation.weight) &&
        Objects.equals(this.name, stopLocation.name) &&
        Objects.equals(this.track, stopLocation.track) &&
        Objects.equals(this.lat, stopLocation.lat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, lon, idx, weight, name, track, lat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopLocation {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    idx: ").append(toIndentedString(idx)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    track: ").append(toIndentedString(track)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

