/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.LocalDate;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * SystemInfo
 */
public class SystemInfo {
  @SerializedName("TimetableInfo")
  private TimetableInfo timetableInfo = null;

  @SerializedName("errorText")
  private String errorText = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("serverdate")
  private LocalDate serverdate = null;

  @SerializedName("servertime")
  private String servertime = null;

  @SerializedName("noNamespaceSchemaLocation")
  private String noNamespaceSchemaLocation = null;

  public SystemInfo timetableInfo(TimetableInfo timetableInfo) {
    this.timetableInfo = timetableInfo;
    return this;
  }

   /**
   * Get timetableInfo
   * @return timetableInfo
  **/
  @ApiModelProperty(value = "")
  public TimetableInfo getTimetableInfo() {
    return timetableInfo;
  }

  public void setTimetableInfo(TimetableInfo timetableInfo) {
    this.timetableInfo = timetableInfo;
  }

  public SystemInfo errorText(String errorText) {
    this.errorText = errorText;
    return this;
  }

   /**
   * Get errorText
   * @return errorText
  **/
  @ApiModelProperty(value = "")
  public String getErrorText() {
    return errorText;
  }

  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  public SystemInfo error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public SystemInfo serverdate(LocalDate serverdate) {
    this.serverdate = serverdate;
    return this;
  }

   /**
   * Get serverdate
   * @return serverdate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getServerdate() {
    return serverdate;
  }

  public void setServerdate(LocalDate serverdate) {
    this.serverdate = serverdate;
  }

  public SystemInfo servertime(String servertime) {
    this.servertime = servertime;
    return this;
  }

   /**
   * Current server time in format HH:MM
   * @return servertime
  **/
  @ApiModelProperty(value = "Current server time in format HH:MM")
  public String getServertime() {
    return servertime;
  }

  public void setServertime(String servertime) {
    this.servertime = servertime;
  }

  public SystemInfo noNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
    return this;
  }

   /**
   * Get noNamespaceSchemaLocation
   * @return noNamespaceSchemaLocation
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNoNamespaceSchemaLocation() {
    return noNamespaceSchemaLocation;
  }

  public void setNoNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemInfo systemInfo = (SystemInfo) o;
    return Objects.equals(this.timetableInfo, systemInfo.timetableInfo) &&
        Objects.equals(this.errorText, systemInfo.errorText) &&
        Objects.equals(this.error, systemInfo.error) &&
        Objects.equals(this.serverdate, systemInfo.serverdate) &&
        Objects.equals(this.servertime, systemInfo.servertime) &&
        Objects.equals(this.noNamespaceSchemaLocation, systemInfo.noNamespaceSchemaLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timetableInfo, errorText, error, serverdate, servertime, noNamespaceSchemaLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemInfo {\n");

    sb.append("    timetableInfo: ").append(toIndentedString(timetableInfo)).append("\n");
    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    serverdate: ").append(toIndentedString(serverdate)).append("\n");
    sb.append("    servertime: ").append(toIndentedString(servertime)).append("\n");
    sb.append("    noNamespaceSchemaLocation: ").append(toIndentedString(noNamespaceSchemaLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

