/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * TimeTablePeriod
 */
public class TimeTablePeriod {
  @SerializedName("DateBegin")
  private DateBegin dateBegin = null;

  @SerializedName("DateEnd")
  private DateEnd dateEnd = null;

  public TimeTablePeriod dateBegin(DateBegin dateBegin) {
    this.dateBegin = dateBegin;
    return this;
  }

   /**
   * Get dateBegin
   * @return dateBegin
  **/
  @ApiModelProperty(required = true, value = "")
  public DateBegin getDateBegin() {
    return dateBegin;
  }

  public void setDateBegin(DateBegin dateBegin) {
    this.dateBegin = dateBegin;
  }

  public TimeTablePeriod dateEnd(DateEnd dateEnd) {
    this.dateEnd = dateEnd;
    return this;
  }

   /**
   * Get dateEnd
   * @return dateEnd
  **/
  @ApiModelProperty(required = true, value = "")
  public DateEnd getDateEnd() {
    return dateEnd;
  }

  public void setDateEnd(DateEnd dateEnd) {
    this.dateEnd = dateEnd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTablePeriod timeTablePeriod = (TimeTablePeriod) o;
    return Objects.equals(this.dateBegin, timeTablePeriod.dateBegin) &&
        Objects.equals(this.dateEnd, timeTablePeriod.dateEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateBegin, dateEnd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTablePeriod {\n");

    sb.append("    dateBegin: ").append(toIndentedString(dateBegin)).append("\n");
    sb.append("    dateEnd: ").append(toIndentedString(dateEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

