/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.togowos.model;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.LocalDate;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * TripList
 */
public class TripList {
  @SerializedName("errorText")
  private String errorText = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("serverdate")
  private LocalDate serverdate = null;

  @SerializedName("servertime")
  private String servertime = null;

  @SerializedName("Trip")
  private List<Trip> trip = null;

  @SerializedName("noNamespaceSchemaLocation")
  private String noNamespaceSchemaLocation = null;

  public TripList errorText(String errorText) {
    this.errorText = errorText;
    return this;
  }

   /**
   * Get errorText
   * @return errorText
  **/
  @ApiModelProperty(value = "")
  public String getErrorText() {
    return errorText;
  }

  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  public TripList error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public TripList serverdate(LocalDate serverdate) {
    this.serverdate = serverdate;
    return this;
  }

   /**
   * Get serverdate
   * @return serverdate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getServerdate() {
    return serverdate;
  }

  public void setServerdate(LocalDate serverdate) {
    this.serverdate = serverdate;
  }

  public TripList servertime(String servertime) {
    this.servertime = servertime;
    return this;
  }

   /**
   * Current server time in format HH:MM
   * @return servertime
  **/
  @ApiModelProperty(value = "Current server time in format HH:MM")
  public String getServertime() {
    return servertime;
  }

  public void setServertime(String servertime) {
    this.servertime = servertime;
  }

  public TripList trip(List<Trip> trip) {
    this.trip = trip;
    return this;
  }

  public TripList addTripItem(Trip tripItem) {
    if (this.trip == null) {
      this.trip = new ArrayList<Trip>();
    }
    this.trip.add(tripItem);
    return this;
  }

   /**
   * Get trip
   * @return trip
  **/
  @ApiModelProperty(value = "")
  public List<Trip> getTrip() {
    return trip;
  }

  public void setTrip(List<Trip> trip) {
    this.trip = trip;
  }

  public TripList noNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
    return this;
  }

   /**
   * Get noNamespaceSchemaLocation
   * @return noNamespaceSchemaLocation
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNoNamespaceSchemaLocation() {
    return noNamespaceSchemaLocation;
  }

  public void setNoNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripList tripList = (TripList) o;
    return Objects.equals(this.errorText, tripList.errorText) &&
        Objects.equals(this.error, tripList.error) &&
        Objects.equals(this.serverdate, tripList.serverdate) &&
        Objects.equals(this.servertime, tripList.servertime) &&
        Objects.equals(this.trip, tripList.trip) &&
        Objects.equals(this.noNamespaceSchemaLocation, tripList.noNamespaceSchemaLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorText, error, serverdate, servertime, trip, noNamespaceSchemaLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripList {\n");

    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    serverdate: ").append(toIndentedString(serverdate)).append("\n");
    sb.append("    servertime: ").append(toIndentedString(servertime)).append("\n");
    sb.append("    trip: ").append(toIndentedString(trip)).append("\n");
    sb.append("    noNamespaceSchemaLocation: ").append(toIndentedString(noNamespaceSchemaLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

