/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.example.togowos.Api.DepartureBoardApi;
import com.example.togowos.model.DepartureBoard;

import org.junit.Ignore;
import org.junit.Test;
import org.threeten.bp.LocalDate;

/**
 * API tests for DepartureBoardApi
 */
@Ignore
public class DepartureBoardApiTest {

    private final DepartureBoardApi api = new DepartureBoardApi();


    /**
     * Return the next 20 departures (or less if not existing) from a given point in time or the next departures in a given timespan.
     *
     * This method will return the next 20 departures (or less if not existing) from a given point in time or the next departures in a given timespan. The service can only be called for stops/stations by using according ID retrieved by the location method. The parameter is called id. The time and date are defined with the parameters date and time.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDepartureBoardTest() throws Exception {
        Long id = null;
        LocalDate date = null;
        String time = null;
        String useVas = null;
        String useLDTrain = null;
        String useRegTrain = null;
        String useBus = null;
        String useBoat = null;
        String useTram = null;
        String excludeDR = null;
        Integer timeSpan = null;
        Integer maxDeparturesPerLine = null;
        String needJourneyDetail = null;
        Long direction = null;
        String format = null;
        String jsonpCallback = null;
        DepartureBoard response = api.getDepartureBoard(id, date, time, useVas, useLDTrain, useRegTrain, useBus, useBoat, useTram, excludeDR, timeSpan, maxDeparturesPerLine, needJourneyDetail, direction, format, jsonpCallback);

        // TODO: test validations
    }

}
