/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.example.togowos.Api.GeometryApi;
import com.example.togowos.model.Geometry;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GeometryApi
 */
@Ignore
public class GeometryApiTest {

    private final GeometryApi api = new GeometryApi();


    /**
     * Returns the polyline for a leg.
     *
     * Returns the polyline for a leg. This service can not be called directly but only by reference URLs in a result of a trip or JourneyDetail request. The result contains a list of WGS84 coordinates which can be used to display the polyline on a map.If the parameter needItinerary&#x3D;1 is passed in the URL of the trip request that contained the reference to the Geometry service, the geometry reference link will also contain an itinerary for walk, bike and car legs, that can be used to generate turn-by-turn instructions.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getGeometryTest() throws Exception {
        String ref = null;
        Geometry response = api.getGeometry(ref);

        // TODO: test validations
    }

}
