/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.example.togowos.Api.JourneyDetailApi;
import com.example.togowos.model.JourneyDetail;

import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for JourneyDetailApi
 */
@Ignore
public class JourneyDetailApiTest {

    private final JourneyDetailApi api = new JourneyDetailApi();


    /**
     * Returns information about the complete route of a trip.
     *
     * Delivers information about the complete route of a trip. This service can not be called directly but only by reference URLs in a result of a trip or departureBoard request. It contains a list of all stops/stations of this journey including all departure and arrival times (with real-time data if available) and additional information like specific attributes about facilities and other texts.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getJourneyDetailTest() throws Exception {
        String ref = null;
        JourneyDetail response = api.getJourneyDetail(ref);

        // TODO: test validations
    }

}
