/*
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import com.example.togowos.Api.LivemapApi;
import com.example.togowos.model.LiveMap;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LivemapApi
 */
@Ignore
public class LivemapApiTest {

    private final LivemapApi api = new LivemapApi();


    /**
     * Returns the positions of all vehicles in a given bounding box
     *
     * This method will return the positions of all vehicles in a given bounding box.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void livemapTest() throws Exception {
        String minx = null;
        String maxx = null;
        String miny = null;
        String maxy = null;
        String onlyRealtime = null;
        LiveMap response = api.livemap(minx, maxx, miny, maxy, onlyRealtime);

        // TODO: test validations
    }

}
